### ISSUE TITLE
3.2.39 (fb2) hidden text formatted with built-in styles

### ISSUE THREAD

**Issue by ssten** [buggins/coolreader#140]
One of historical advantages of CoolReader was the support of styling, including built-in styles for spacing text formatting.

In 3.2.39 this feature is broken.

I.e. file:

```
<?xml version="1.0" encoding="utf-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
<stylesheet type="text/css">
  style[name="razryadka"] {
  letter-spacing: 0.4em;
  }
</stylesheet>
  <description>
…
<p>One, <style name="razryadka">two</style>, three.</p>
…
```

Displays only:

> One, , three.

**Comment by poire-z** [comment]
Didn't know that `<style>` was a proper FB2 element.
In EPUB, it's mostly used in the `<HEAD>` element, and I had hardcoded it to be hidden by default (because when disabling stylesheets, it would otherwise show):
https://github.com/buggins/coolreader/blob/26014a17806d91615d48214d19d29579c8992d42/crengine/include/fb2def.h#L48

You can have it working again I think by adding in fb2.css:
```css
style { display: inline; }
```

**Comment by virxkane** [comment]
Fixed.
Screenshot from current master branch:
![Screenshot_20210820_092937](https://user-images.githubusercontent.com/36960933/130184263-ce1e555c-6f80-4aa6-b625-60dda259125d.png)
