### ISSUE TITLE
Merge with KOReader fork of crengine

### ISSUE THREAD

**Issue by link2xt** [buggins/coolreader#91]
KOReader developers (ping @Frenzie @poire-z) maintain a fork of crengine: https://github.com/koreader/crengine/ Quick diff shows that there are list item display fixes (see #90), several new CSS properties support, fix for `<cite>` bug (https://sourceforge.net/p/crengine/bugs/268/) and other enhancements. Are there any plans to merge these fixes back into coolreader?

Related issue about another fork: https://github.com/koreader/crengine/issues/267

(KOReader is great, but it focuses on e-ink devices, so it does not even support changing background color. For this reason, it can't be used as a drop-in replacement for CoolReader on Android.)

**Comment by Frenzie** [comment]
To provide some context, upstream was regrettably inactive for several years, which led to our divergence from it. We've had good improvements in HTML and CSS conformance over at the KOReader fork during that time, as well as speed. (Plus some nifty additional features like user style tweaks.) Since this very GH repository revived upstream it has given us HarfBuzz, which is also very neat.

Our crengine code itself purposefully has diverged fairly little from its source material (or has used preprocessor statements, e.g., in https://github.com/koreader/crengine/pull/282), so it might not be too problematic to integrate it with the updated Java/Qt frontends.
